DROP TABLE IF EXISTS LOANS;

CREATE TABLE LOANS(
	LOAN_ID INT PRIMARY KEY AUTO_INCREMENT,
	CUSTOMER_ID INT,
	LOAN_TYPE VARCHAR2(100),
	START_DATE DATE,
	TOTAL_AMOUNT INT,
	PAID_AMOUNT INT,
	OUTSTANDING_AMOUNT INT,
	CREATED_TS DATE
);

INSERT INTO LOANS(LOAN_ID,CUSTOMER_ID,LOAN_TYPE,START_DATE,TOTAL_AMOUNT,PAID_AMOUNT,OUTSTANDING_AMOUNT,CREATED_TS) VALUES
(123, 1, 'Education', sysdate, 1000000, 700000, 300000, sysdate);

INSERT INTO LOANS(LOAN_ID,CUSTOMER_ID,LOAN_TYPE,START_DATE,TOTAL_AMOUNT,PAID_AMOUNT,OUTSTANDING_AMOUNT,CREATED_TS) VALUES
(124, 1, 'House', sysdate, 1000000, 700000, 300000, sysdate);

INSERT INTO LOANS(LOAN_ID,CUSTOMER_ID,LOAN_TYPE,START_DATE,TOTAL_AMOUNT,PAID_AMOUNT,OUTSTANDING_AMOUNT,CREATED_TS) VALUES
(125, 1, 'Vehicle', sysdate, 1000000, 700000, 300000, sysdate);

INSERT INTO LOANS(LOAN_ID,CUSTOMER_ID,LOAN_TYPE,START_DATE,TOTAL_AMOUNT,PAID_AMOUNT,OUTSTANDING_AMOUNT,CREATED_TS) VALUES
(126, 1, 'House', sysdate, 1000000, 700000, 300000, sysdate);

commit;